spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: apps
    password: apps
    url: jdbc:oracle:thin:@erpoda04-base.yfy.corp:1521:TUAT1
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.H2Dialect


logging:
 file: my.log
 config:
  classpath: logback-boot.xml


