package com.tx.yfy.ws.com.oracle.xmlns.mailnotificationbpelprocess;

import com.tx.yfy.ws.CHPMailNotificationRequestType;
import com.tx.yfy.ws.ObjectFactory;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-07-31T18:04:09.300+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/YFY_CHP_SOA/UTL_CHP_EmailNotificationService/MailNotificationBPELProcess", name = "MailNotificationBPELProcess")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MailNotificationBPELProcess {

    @WebMethod(action = "process")
    @Oneway
    public void process(
        @WebParam(partName = "payload", name = "CHPMailNotificationRequest", targetNamespace = "http://yfy.com/SOA/XXIF/CHPMailNotifProcess")
        CHPMailNotificationRequestType payload
    );
}
