//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.08 at 02:07:28 PM CST 
//


package com.tx.yfy.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tx.yfy.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CHPMailNotificationRequest_QNAME = new QName("http://yfy.com/SOA/XXIF/CHPMailNotifProcess", "CHPMailNotificationRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tx.yfy.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CHPMailNotificationRequestType }
     * 
     */
    public CHPMailNotificationRequestType createCHPMailNotificationRequestType() {
        return new CHPMailNotificationRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHPMailNotificationRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://yfy.com/SOA/XXIF/CHPMailNotifProcess", name = "CHPMailNotificationRequest")
    public JAXBElement<CHPMailNotificationRequestType> createCHPMailNotificationRequest(CHPMailNotificationRequestType value) {
        return new JAXBElement<CHPMailNotificationRequestType>(_CHPMailNotificationRequest_QNAME, CHPMailNotificationRequestType.class, null, value);
    }

}
