//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.08 at 02:07:28 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://yfy.com/SOA/XXIF/CHPMailNotifProcess", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tx.yfy.ws;
